### ISSUE TITLE
ErrorException in AbstractProvider.php line 32

### ISSUE THREAD

**Issue by craigcartmell** [SocialiteProviders/Goodreads#1]
Tracing it through, I think it could possibly be trying to build an oAuth 2 provider but I'm not entirely sure. 

Also note, I'm using **Lumen** and not Laravel. Spotify and Strava are working fine if it's any help.

¬Argument 2 passed to Laravel\Socialite\One\AbstractProvider::__construct() must be an instance of League\OAuth1\Client\Server\Server, string given, called in /home/vagrant/projects/test-api/vendor/laravel/socialite/src/SocialiteManager.php on line 83 and defined`

**Comment by DraperStudio** [comment]
Could you maybe go into `vendor/socialiteproviders/manager/src/SocialiteWasCalled.php` and check for this line `if ($this->isOAuth1($oauth1Server)) {`.

If you found it could you do a `dd($this->isOAuth1($oauth1Server));` aboven this line and tell me what it return you. Will need to setup a test-app later to test it myself with Lumen.

**Comment by craigcartmell** [comment]
Ah, looks like I'm using an old version of the socialiteproviders/manager!

I haven't been able to test it yet but I'll close this for now.
